---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: russian
  name: russian
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ2aW91c2Vydm13YXJlIiwicGFzc3dvcmQiOiJWTXdhcmUxMjM0NSEiLCJlbWFpbCI6InZpb3VzZXIudm13YXJlQGdtYWlsLmNvbSIsImF1dGgiOiJkbWx2ZFhObGNuWnRkMkZ5WlRwV1RYZGhjbVV4TWpNME5TRT0ifX19
kind: Secret
metadata:
  name: dockerhub-image-pull-secret
  namespace: russian
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: russian 
  namespace: russian 
imagePullSecrets:
- name: dockerhub-image-pull-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: russian 
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: russian 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: russian
subjects:
- kind: ServiceAccount
  name: russian 
  namespace: russian 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ai-inference
  name: ai-inference
  namespace: russian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-inference
  template:
    metadata:
      labels:
        app: ai-inference
    spec:
      serviceAccountName: russian 
      containers:
      - image: viouservmware/ecs-cv:v1
        command: ["python3", "-u", "/usr/src/app/app.py"]
        imagePullPolicy: Always
        name: ai-inference
        ports:
        - containerPort: 7860
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ai-inference
  name: ai-inference
  namespace: russian
spec:
  ports:
  - nodePort: 30333
    port: 7860
    protocol: TCP
    targetPort: 7860
  selector:
    app: ai-inference
  type: NodePort

